---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xpertiap/vacunas.xpertiaplus.com/
    - echo "Desplegando frontend en $DEPLOYPATH"
    - /bin/cp -r ./dist/spa/* $DEPLOYPATH
    - echo "Frontend desplegado exitosamente en $DEPLOYPATH"
