---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xpertiab/public_html/frontvacunas.xpertiabo.com/
    - echo "Desplegando frontend en $DEPLOYPATH"
    - /bin/cp -r ./build/* $DEPLOYPATH
    - echo "Frontend desplegado exitosamente en $DEPLOYPATH"
